In [1]:
import torch 

In [2]:
print(torch.__version__)

2.6.0+cu124


In [3]:
a  = torch.empty(2,3)
#the attribute size is a row and then a column 

In [4]:
print(a)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.1221e+36, 4.2941e-41]])


In [5]:
type(a)

torch.Tensor

In [6]:
(torch.zeros(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
(torch.ones(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.2339, 0.1154, 0.6153],
        [0.3766, 0.2201, 0.4064]])

In [9]:
A = torch.rand(2,3)
print(A)


tensor([[0.0343, 0.0381, 0.0291],
        [0.4257, 0.7180, 0.6870]])


In [10]:
B = torch.rand(2,3)
print(A+B)

tensor([[0.7163, 0.7981, 0.0540],
        [0.8280, 0.9729, 0.8546]])


In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
A = torch.tensor([[1,2,3],[4,5,6]])

In [13]:
A.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(A)

tensor([[131617247047056, 131617247047056,              32],
        [            112, 100799499929772,      4294967296]])

In [15]:
torch.zeros_like(A)

tensor([[0, 0, 0],
        [0, 0, 0]])